# Generated by Django 4.0.4 on 2022-06-14 13:34

import django.contrib.postgres.search
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published', models.BooleanField(default=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('-', 'Other'), ('X', 'Unknown')], max_length=1, null=True, verbose_name='abstract.gender')),
                ('lbauthorid', models.CharField(blank=True, max_length=128, null=True)),
                ('normalized_lbauthorid', models.CharField(blank=True, max_length=128, null=True)),
                ('name', models.CharField(blank=True, max_length=128, null=True, verbose_name='litteraturlabbet.author.name')),
                ('formatted_name', models.CharField(blank=True, max_length=128, null=True, verbose_name='litteraturlabbet.author.formatted_name')),
                ('surname', models.CharField(blank=True, max_length=128, null=True, verbose_name='litteraturlabbet.author.surname')),
                ('birth_year', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='litteraturlabbet.author.birth_year')),
                ('birth_year_plain', models.CharField(blank=True, max_length=4, null=True, verbose_name='litteraturlabbet.author.birth_year_plain')),
                ('death_year', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='litteraturlabbet.author.death_year')),
                ('death_year_plain', models.CharField(blank=True, max_length=4, null=True, verbose_name='litteraturlabbet.author.death_year_plain')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published', models.BooleanField(default=True)),
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('size', models.PositiveIntegerField(verbose_name='litteraturlabbet.cluster.size')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published', models.BooleanField(default=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('text', models.TextField(default='')),
                ('text_vector', django.contrib.postgres.search.SearchVectorField(null=True)),
                ('number', models.PositiveIntegerField(verbose_name='litteraturlabbet.cluster.size')),
            ],
            options={
                'ordering': ['-number'],
            },
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published', models.BooleanField(default=True)),
                ('title', models.CharField(default='', max_length=256, verbose_name='litteraturlabbet.work.title')),
                ('short_title', models.CharField(blank=True, max_length=128, null=True, verbose_name='litteraturlabbet.work.short_title')),
                ('modernized_title', models.CharField(blank=True, max_length=256, null=True, verbose_name='littearturlabbet.work.modernized_title')),
                ('lbworkid', models.CharField(max_length=64, unique=True, verbose_name='litteraturlabbet.work.lbworkid')),
                ('librisid', models.CharField(blank=True, max_length=64, null=True, verbose_name='litteraturlabbet.work.librisid')),
                ('edition', models.CharField(blank=True, max_length=64, null=True, verbose_name='litteraturlabbet.work.edition')),
                ('language', models.CharField(blank=True, max_length=64, null=True, verbose_name='litteraturlabbet.work.language')),
                ('word_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='litteraturlabbet.work.word_count')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='litteraturlabbet.author', verbose_name='litteraturlabbet.work.author')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published', models.BooleanField(default=True)),
                ('uid', models.IntegerField(unique=True)),
                ('gid', models.IntegerField(unique=True)),
                ('bw', models.PositiveIntegerField(verbose_name='litteraturlabbet.segment.bw')),
                ('ew', models.PositiveIntegerField(verbose_name='litteraturlabbet.segment.ew')),
                ('begin', models.PositiveIntegerField(verbose_name='litteraturlabbet.segment.begin')),
                ('end', models.PositiveIntegerField(verbose_name='litteraturlabbet.segment.end')),
                ('text', models.TextField(default='', verbose_name='litteraturlabbet.segment.text')),
                ('series', models.CharField(max_length=64, verbose_name='litteraturlabbet.segment.series')),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='litteraturlabbet.cluster', verbose_name='litteraturlabbet.segment.cluster')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='litteraturlabbet.page', verbose_name='litteraturlabbet.segment.page')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='page',
            name='work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='litteraturlabbet.work', verbose_name='litteraturlabbet.work.work'),
        ),
        migrations.AddConstraint(
            model_name='page',
            constraint=models.UniqueConstraint(fields=('work', 'number'), name='unique page-work identifier'),
        ),
    ]
