# Generated by Django 4.0.4 on 2022-06-14 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('litteraturlabbet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='edition',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='litteraturlabbet.work.edition'),
        ),
        migrations.AlterField(
            model_name='work',
            name='language',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='litteraturlabbet.work.language'),
        ),
        migrations.AlterField(
            model_name='work',
            name='lbworkid',
            field=models.CharField(max_length=128, unique=True, verbose_name='litteraturlabbet.work.lbworkid'),
        ),
        migrations.AlterField(
            model_name='work',
            name='librisid',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='litteraturlabbet.work.librisid'),
        ),
        migrations.AlterField(
            model_name='work',
            name='modernized_title',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='littearturlabbet.work.modernized_title'),
        ),
        migrations.AlterField(
            model_name='work',
            name='short_title',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='litteraturlabbet.work.short_title'),
        ),
        migrations.AlterField(
            model_name='work',
            name='title',
            field=models.CharField(default='', max_length=512, verbose_name='litteraturlabbet.work.title'),
        ),
    ]
