# Generated by Django 4.0.4 on 2022-06-14 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('litteraturlabbet', '0002_alter_work_edition_alter_work_language_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='modernized_title',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='littearturlabbet.work.modernized_title'),
        ),
        migrations.AlterField(
            model_name='work',
            name='title',
            field=models.CharField(default='', max_length=1024, verbose_name='litteraturlabbet.work.title'),
        ),
    ]
