# Generated by Django 4.0.4 on 2022-06-14 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('litteraturlabbet', '0003_alter_work_modernized_title_alter_work_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='title',
            field=models.CharField(blank=True, default='', max_length=1024, null=True, verbose_name='litteraturlabbet.work.title'),
        ),
    ]
